"""Add Procedure model

Revision ID: 070921c4c9c9
Revises: 76828eb36d00
Create Date: 2024-10-31 00:29:57.860817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070921c4c9c9'
down_revision = '76828eb36d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=20), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('duration')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
