"""Add client_name to booking table

Revision ID: ec7e4908940b
Revises: e5b2dc3cff57
Create Date: 2024-11-25 03:15:07.130529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7e4908940b'
down_revision = 'e5b2dc3cff57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('client_name')

    # ### end Alembic commands ###
